### ISSUE TITLE
How to build this project ?

### ISSUE THREAD

**Issue by Anil-matcha** [jessuni/shikwasa#26]
Hey, thanks for this cool project. I tried to run an example and it was working great but I was not able to change theme color or theme using options. To test it out I tried to build the project but the build is failing. 

Can you kindly let me know the way to build the project ? I tried to run "npm run build" but it gives me the below error

> shikwasa@2.0.1 build C:\Users\srini\Downloads\shikwasa
> npm run build:main && npm run build:chapter

> shikwasa@2.0.1 build:main C:\Users\srini\Downloads\shikwasa
> TARGET=main rollup -c

'TARGET' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jessuni** [comment]
I've updated a fiddle to demonstrate how to use `themeColor` and `theme`: https://jsfiddle.net/jessuni/netgvbwy/8/

As for the building process, the latest [CI](https://github.com/jessuni/shikwasa/runs/1641604211?check_suite_focus=true) showed not error in remotely building the library, so the error is unlikely to come from the script. `TARGET` represents the env variable `TARGET` which you can access by `process.env.TARGET`. Try setting up the env variable in your local environment. 
If you're using Windows, instead of
`TARGET=`
try
`SET TARGET=development`

**Comment by Anil-matcha** [comment]
Hi @jessuni 
Thanks for the reply. After using SET TARGET=main and TARGET=chapter locally and then running rollup.c helped me in building on Windows. Thanks again for the help. 

Closing this issue now
