### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by zincurat** [jessuni/shikwasa#28]
Hi! This is the most beautiful podcast player I have seen!  I didn't find mentions about playlists in the roadmap, will be they added? This will be really wonderful!

**Comment by jessuni** [comment]
Thanks for the request! The playlist feature was previously listed in the roadmap but got removed because no one ever requested it. If more people need this feature I'll add it back in. But as I'm currently working on other features, I could't spare much effort in this one (mainly because UI design is so time-consuming).

However, all the methods needed to make a playlist works are available. As a workaround you can make your own playlist call `.update(audio)` to achieve the same purpose.

**Comment by zincurat** [comment]
Thanks for answer! I will follow your project and good luck in your work!

**Comment by smilingpeanut** [comment]
I wouldn't mind seeing this as well! But I understand there are other items that are more pressing.

**Comment by Anil-matcha** [comment]
Would love playlist feature to be added

**Comment by candidexmedia** [comment]
+1 for a playlist
