### ISSUE TITLE
When destroying the player instance, an error occurred - Uncaught TypeError: Cannot read properties of null (reading 'currentTime').

### ISSUE THREAD

**Issue by divyansh-tracxn** [jessuni/shikwasa#60]
While destroying the player instance, the player throws an error.

To reproduce the problem, follow these steps:

1) Create a player instance first.
2) Destroy instance(`player.destroy()`) .

Or visit this [js-fiddle](https://jsfiddle.net/35vmbtwh/) link where this issue is reproducing.
Please investigate this.

![Screenshot from 2022-05-31 09-44-05](https://user-images.githubusercontent.com/105422938/171091518-394747b2-f56d-4a76-9cd7-8192265b2112.png)

**Comment by LGiki** [comment]
Encountered the same error. I did some simple investigation.

---

`player.destroy()` calls `this.destroyAudio()`:

https://github.com/jessuni/shikwasa/blob/446b28e03ed5f150558a4161ac1c4105693880db/src/player.js#L394-L404

`this.destroyAudio()` sets `this.audio.src` to `''` and sets the `this.audio` to null:

https://github.com/jessuni/shikwasa/blob/446b28e03ed5f150558a4161ac1c4105693880db/src/player.js#L387-L392

The change in `this.audio.src` triggers the `timeupdate` event. In the callback function of the `timeupdate` event, it reads `this.audio.currentTime` which caused this error. Because `this.audio` is set to null by `this.destroyAudio()`.

https://github.com/jessuni/shikwasa/blob/446b28e03ed5f150558a4161ac1c4105693880db/src/player.js#L259-L263

So a quick fix would be to check if `this.audio` is null in the `timeupdate` callback function:

```javascript
this.on('timeupdate', () => {
  if (this.audio && !this._dragging) {
    this.ui.setProgress(this.audio.currentTime, null, this.duration)
  }
})
```

But it might be better to remove all event listeners in `player.destroy()`.

**Comment by jessuni** [comment]
Bug fixed. Closing this issue

**Comment by divyansh-tracxn** [comment]
Version is not published for this fix, please publish the library

**Comment by jessuni** [comment]
Yeah, sorry for the delay. I had to add the tests and pass them before publishing.
